server:
  port: 8082

spring:
  config:
    activate:
      on-profile: default
  application:
    name: resources
  datasource:
    url: jdbc:mysql://${resources-db:localhost}:3308/resources-db
    username: root
    password: 12345
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

app:
  environment:
    gateway-host: ${gateway-host:localhost}


--- # Testing configuration

server:
  port: ${random.int(5000,5100)}

spring:
  cloud:
    service-registry:
      auto-registration:
        enabled: false
  config:
    activate:
      on-profile: test
  application:
    name: resources
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: root
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    enabled: false

app:
  environment:
    empleados-host: none
    nominas-host: none
    transferencias-host: none
